/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlayRouteImport } from './routes/play'
import { Route as MoreGamesRouteImport } from './routes/more-games'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLeaderboardSubmitRouteImport } from './routes/api/public/leaderboard/submit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreGamesRoute = MoreGamesRouteImport.update({
  id: '/more-games',
  path: '/more-games',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeaderboardSubmitRoute =
  ApiPublicLeaderboardSubmitRouteImport.update({
    id: '/api/public/leaderboard/submit',
    path: '/api/public/leaderboard/submit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/more-games': typeof MoreGamesRoute
  '/play': typeof PlayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/leaderboard/submit': typeof ApiPublicLeaderboardSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/more-games': typeof MoreGamesRoute
  '/play': typeof PlayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/leaderboard/submit': typeof ApiPublicLeaderboardSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/more-games': typeof MoreGamesRoute
  '/play': typeof PlayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/leaderboard/submit': typeof ApiPublicLeaderboardSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/more-games'
    | '/play'
    | '/sitemap.xml'
    | '/api/public/leaderboard/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/more-games'
    | '/play'
    | '/sitemap.xml'
    | '/api/public/leaderboard/submit'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/more-games'
    | '/play'
    | '/sitemap.xml'
    | '/api/public/leaderboard/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MoreGamesRoute: typeof MoreGamesRoute
  PlayRoute: typeof PlayRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicLeaderboardSubmitRoute: typeof ApiPublicLeaderboardSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more-games': {
      id: '/more-games'
      path: '/more-games'
      fullPath: '/more-games'
      preLoaderRoute: typeof MoreGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leaderboard/submit': {
      id: '/api/public/leaderboard/submit'
      path: '/api/public/leaderboard/submit'
      fullPath: '/api/public/leaderboard/submit'
      preLoaderRoute: typeof ApiPublicLeaderboardSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MoreGamesRoute: MoreGamesRoute,
  PlayRoute: PlayRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicLeaderboardSubmitRoute: ApiPublicLeaderboardSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
